/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.latihangui.view;

import static java.lang.System.in;
import static javax.management.Query.in;
import javax.swing.JOptionPane;

/**
 *
 * @author Ajayfaul
 */
public class MainmenuView extends javax.swing.JFrame {

    /**
     * Creates new form MainmenuView
     */
    public MainmenuView() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        btnPlanet = new javax.swing.JLabel();
        btnRocket1 = new javax.swing.JLabel();
        btnRocket3 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Planet = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPilih1 = new javax.swing.JButton();
        btnPilih2 = new javax.swing.JButton();
        btnPilih3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnPilih4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnPilih5 = new javax.swing.JButton();
        btnPilih6 = new javax.swing.JButton();
        btnPilih7 = new javax.swing.JButton();
        Rocket = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(43, 38, 57));

        menuPanel.setBackground(new java.awt.Color(43, 38, 57));

        Menu.setBackground(new java.awt.Color(26, 188, 156));

        jLabel1.setFont(new java.awt.Font("Coolvetica Rg", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SPACETRIP");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ajayfaul\\Pictures\\Home_64px.png")); // NOI18N
        btnHome.setText("Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        btnPlanet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPlanet.setForeground(new java.awt.Color(255, 255, 255));
        btnPlanet.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ajayfaul\\Pictures\\Planet_64px.png")); // NOI18N
        btnPlanet.setText("Planet");
        btnPlanet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlanetMouseClicked(evt);
            }
        });

        btnRocket1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRocket1.setForeground(new java.awt.Color(255, 255, 255));
        btnRocket1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ajayfaul\\Pictures\\Rocket_64px.png")); // NOI18N
        btnRocket1.setText("Rocket");
        btnRocket1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRocket1MouseClicked(evt);
            }
        });

        btnRocket3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRocket3.setForeground(new java.awt.Color(255, 255, 255));
        btnRocket3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ajayfaul\\Pictures\\About_64px.png")); // NOI18N
        btnRocket3.setText("About");
        btnRocket3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRocket3MouseClicked(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(43, 38, 57));
        mainPanel.setLayout(new java.awt.CardLayout());

        Home.setBackground(new java.awt.Color(43, 38, 57));

        jLabel2.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Our Home is Earth ");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ajayfaul\\Pictures\\earth.png")); // NOI18N

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel3))
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(1774, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        mainPanel.add(Home, "card2");

        Planet.setBackground(new java.awt.Color(43, 38, 57));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ajayfaul\\Pictures\\venus.jpg")); // NOI18N
        jLabel5.setText("Venus");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ajayfaul\\Pictures\\mars.jpg")); // NOI18N
        jLabel6.setText("Mars");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ajayfaul\\Pictures\\merkurius.jpg")); // NOI18N
        jLabel7.setText("Merkurius");

        jLabel4.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pilih Destinasi Planet");

        btnPilih1.setText("Pilih");
        btnPilih1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilih1ActionPerformed(evt);
            }
        });

        btnPilih2.setText("Pilih");
        btnPilih2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilih2ActionPerformed(evt);
            }
        });

        btnPilih3.setText("Pilih");
        btnPilih3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilih3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ajayfaul\\Pictures\\yupiter.jpg")); // NOI18N
        jLabel8.setText("Yupiter");

        btnPilih4.setText("Pilih");
        btnPilih4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilih4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ajayfaul\\Pictures\\saturn.jpg")); // NOI18N
        jLabel9.setText("Saturnus");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ajayfaul\\Pictures\\uranus.jpg")); // NOI18N
        jLabel10.setText("Uranus");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ajayfaul\\Pictures\\neptun.jpg")); // NOI18N
        jLabel11.setText("Neptunus");

        btnPilih5.setText("Pilih");
        btnPilih5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilih5ActionPerformed(evt);
            }
        });

        btnPilih6.setText("Pilih");
        btnPilih6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilih6ActionPerformed(evt);
            }
        });

        btnPilih7.setText("Pilih");
        btnPilih7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilih7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PlanetLayout = new javax.swing.GroupLayout(Planet);
        Planet.setLayout(PlanetLayout);
        PlanetLayout.setHorizontalGroup(
            PlanetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlanetLayout.createSequentialGroup()
                .addGroup(PlanetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PlanetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PlanetLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4))
                        .addGroup(PlanetLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(PlanetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addGroup(PlanetLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel5)))
                            .addGroup(PlanetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PlanetLayout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PlanetLayout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(btnPilih2))))
                        .addGroup(PlanetLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel10)
                            .addGap(35, 35, 35)
                            .addComponent(jLabel11))
                        .addGroup(PlanetLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(btnPilih5)
                            .addGap(133, 133, 133)
                            .addComponent(btnPilih6)
                            .addGap(139, 139, 139)
                            .addComponent(btnPilih7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PlanetLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnPilih1)
                        .addGap(141, 141, 141)
                        .addComponent(btnPilih3)
                        .addGap(129, 129, 129)
                        .addComponent(btnPilih4)))
                .addContainerGap(1628, Short.MAX_VALUE))
        );
        PlanetLayout.setVerticalGroup(
            PlanetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlanetLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(68, 68, 68)
                .addGroup(PlanetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(PlanetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPilih1)
                    .addComponent(btnPilih3)
                    .addComponent(btnPilih4))
                .addGap(18, 18, 18)
                .addGroup(PlanetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPilih2))
                .addGap(37, 37, 37)
                .addGroup(PlanetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PlanetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPilih5)
                    .addComponent(btnPilih6)
                    .addComponent(btnPilih7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(Planet, "card3");

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Coolvetica Rg", 0, 36)); // NOI18N
        jLabel12.setText("Let's go to space using a Rocket");

        javax.swing.GroupLayout RocketLayout = new javax.swing.GroupLayout(Rocket);
        Rocket.setLayout(RocketLayout);
        RocketLayout.setHorizontalGroup(
            RocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RocketLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel12)
                .addContainerGap(1627, Short.MAX_VALUE))
        );
        RocketLayout.setVerticalGroup(
            RocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RocketLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel12)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        mainPanel.add(Rocket, "card4");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ajayfaul\\Pictures\\Sign Out_32px.png")); // NOI18N
        jButton1.setText("Sign Out");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlanet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRocket1)
                        .addGap(27, 27, 27)
                        .addComponent(btnRocket3))
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPlanet, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRocket1)
                        .addComponent(btnRocket3)))
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPilih3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilih3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Venus Dipilih");
    }//GEN-LAST:event_btnPilih3ActionPerformed

    private void btnPilih1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilih1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Merkurius Dipilih");
    }//GEN-LAST:event_btnPilih1ActionPerformed

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        
        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // add panel
        mainPanel.add(Home);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnPlanetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanetMouseClicked
        // TODO add your handling code here:
        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // add panel
        mainPanel.add(Planet);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnPlanetMouseClicked

    private void btnRocket1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRocket1MouseClicked
        // TODO add your handling code here:
        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // add panel
        mainPanel.add(Rocket);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnRocket1MouseClicked

    private void btnPilih4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilih4ActionPerformed
        // TODO add your handling code here:5
        JOptionPane.showMessageDialog(null, "Mars Dipilih");
    }//GEN-LAST:event_btnPilih4ActionPerformed

    private void btnPilih2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilih2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Yupiter Dipilih");
    }//GEN-LAST:event_btnPilih2ActionPerformed

    private void btnPilih5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilih5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Saturnus Dipilih");
    }//GEN-LAST:event_btnPilih5ActionPerformed

    private void btnPilih6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilih6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Uranus Dipilih");
    }//GEN-LAST:event_btnPilih6ActionPerformed

    private void btnPilih7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilih7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Neptunus Dipilih");
    }//GEN-LAST:event_btnPilih7ActionPerformed

    private void btnRocket3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRocket3MouseClicked
        // TODO add your handling code here:
        AboutView n = new AboutView();
        n.setVisible(true);
    }//GEN-LAST:event_btnRocket3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Anda telah Logout!");
        dispose();
        LoginView n = new LoginView();
        n.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainmenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainmenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainmenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainmenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainmenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Planet;
    private javax.swing.JPanel Rocket;
    private javax.swing.JLabel btnHome;
    private javax.swing.JButton btnPilih1;
    private javax.swing.JButton btnPilih2;
    private javax.swing.JButton btnPilih3;
    private javax.swing.JButton btnPilih4;
    private javax.swing.JButton btnPilih5;
    private javax.swing.JButton btnPilih6;
    private javax.swing.JButton btnPilih7;
    private javax.swing.JLabel btnPlanet;
    private javax.swing.JLabel btnRocket1;
    private javax.swing.JLabel btnRocket3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
